[package]
name = "tale"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.3", features = ["derive"] }
colored = "2"
rev_lines = "0.3.0"
soft-ascii-string = "=0.1.1"
